/**
 * Single source of truth for the app's security headers.
 *
 * The same values are consumed by three deploy targets:
 *   - server.js            (Express, local + self-hosted)
 *   - public/_headers      (Netlify)
 *   - vercel.json          (Vercel)
 *
 * Only this file is edited by hand. The other two are generated by
 * `scripts/generate-headers.js` (run via `npm run build`, verified in CI
 * with `--check`) so the three can never drift apart again.
 */

// Content-Security-Policy directives.
// 'unsafe-eval' and blob: are required by the Stockfish WASM engine, which
// compiles WebAssembly and runs from a blob-backed Web Worker.
// Neither script-src nor style-src carries 'unsafe-inline': the page has no
// inline script and no style attributes in the markup. style-src does not
// restrict styles set from JavaScript, which is how the board, the arrows and
// the edit palette are positioned.
const cspDirectives = {
	"default-src": ["'self'"],
	"script-src": ["'self'", "'unsafe-eval'", "blob:"],
	"style-src": ["'self'"],
	"img-src": ["'self'", "data:"],
	"connect-src": ["'self'", "blob:"],
	"font-src": ["'self'", "data:"],
	"object-src": ["'none'"],
	"worker-src": ["'self'", "blob:"],
	"upgrade-insecure-requests": [],
};

/** Serialize the directives into a Content-Security-Policy header value. */
function cspHeaderValue() {
	return Object.entries(cspDirectives)
		.map(([name, values]) =>
			values.length ? `${name} ${values.join(" ")}` : name,
		)
		.join("; ");
}

/**
 * Every response header the app sends, in the order they are emitted.
 * Cross-origin isolation (COEP + COOP) is what enables SharedArrayBuffer,
 * which the multi-threaded Stockfish build needs.
 */
function securityHeaders() {
	return {
		"Content-Security-Policy": cspHeaderValue(),
		"Cross-Origin-Embedder-Policy": "require-corp",
		"Cross-Origin-Opener-Policy": "same-origin",
		"Cross-Origin-Resource-Policy": "same-origin",
		"X-Frame-Options": "DENY",
		"X-Content-Type-Options": "nosniff",
		"Referrer-Policy": "no-referrer",
		"Permissions-Policy": "camera=(), microphone=(), geolocation=()",
	};
}

module.exports = { cspDirectives, cspHeaderValue, securityHeaders };
